### PR TITLE
Allow the user to create an album in Photos from the currently filtered/sorted view of the FaceGrid

### PR DESCRIPTION
**Pull request by dxclancy**
PhotoLibraryAPI
- Add PhotoLibraryAPI as a repository of actions on the PhotoLibrary
- add createAlbum

FaceGrid
- Add a button to make an album

ModelData
-  prevent crashes by protecting against missing attributes - we may want to just remove the printout and ignore them

### CODE REVIEW

**Comment by dxclancy** [comment]
I'm also trying to figure out how to get my unnamed faces named easily.  

Not sure if you'd be interested in this, but thought I'd send it your way.

**Comment by TimFelixBeyer** [comment]
Looks like super cool work, thank you! 
I‘m currently extremely busy, but will take a look as soon as I find some time.

**Comment by TimFelixBeyer** [comment]
Just had another look at your code - the album functionality is super useful, and being more robust to missing attributes is great too!

I went ahead and implemented some more changes like album naming and cleaned up the code somewhat - you've given me push permission to your main branch and I just want to make sure you're happy with me adding some changes before merging.

Thanks for your PR!

**Comment by TimFelixBeyer** [comment]
I'll just merge for now - I hope that's ok!

**Pull request merged**
